In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv("C:/Users/ShreeyaKavali/OneDrive/Desktop/projects/collegerank predictor/iit-and-nit-colleges-admission-criteria-version-2.csv")
df.tail()

Unnamed: 0  year institute_type  round_no quota            pool  \
64953       64953  2021            NIT         1    JK     Female-Only   
64954       64954  2021            NIT         1    JK  Gender-Neutral   
64955       64955  2021            NIT         1    JK     Female-Only   
64956       64956  2021            NIT         1    LA  Gender-Neutral   
64957       64957  2021            NIT         1    LA     Female-Only   

      institute_short                               program_name  \
64953    NIT-Srinagar  Electronics and Communication Engineering   
64954    NIT-Srinagar  Electronics and Communication Engineering   
64955    NIT-Srinagar  Electronics and Communication Engineering   
64956    NIT-Srinagar  Electronics and Communication Engineering   
64957    NIT-Srinagar  Electronics and Communication Engineering   

      program_duration degree_short category  opening_rank  closing_rank  \
64953          4 Years       B.Tech       SC         14185         24048   
64954          4 Years       B.Tech       ST          2736          4171   
64955          4 Years       B.Tech       ST         10870         10870   
64956          4 Years       B.Tech      GEN        166453        265454   
64957          4 Years       B.Tech      GEN        215054        215054   

       is_preparatory  
64953               0  
64954               0  
64955               0  
64956               0  
64957               0

In [5]:
df.head()

Unnamed: 0  year institute_type  round_no quota            pool  \
0           0  2016            IIT         6    AI  Gender-Neutral   
1           1  2016            IIT         6    AI  Gender-Neutral   
2           2  2016            IIT         6    AI  Gender-Neutral   
3           3  2016            IIT         6    AI  Gender-Neutral   
4           4  2016            IIT         6    AI  Gender-Neutral   

  institute_short           program_name program_duration degree_short  \
0      IIT-Bombay  Aerospace Engineering          4 Years       B.Tech   
1      IIT-Bombay  Aerospace Engineering          4 Years       B.Tech   
2      IIT-Bombay  Aerospace Engineering          4 Years       B.Tech   
3      IIT-Bombay  Aerospace Engineering          4 Years       B.Tech   
4      IIT-Bombay  Aerospace Engineering          4 Years       B.Tech   

  category  opening_rank  closing_rank  is_preparatory  
0      GEN           838          1841               0  
1  OBC-NCL           408          1098               0  
2       SC           297           468               0  
3       ST            79           145               0  
4  GEN-PWD            94            94               0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64958 entries, 0 to 64957
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Unnamed: 0        64958 non-null  int64 
 1   year              64958 non-null  int64 
 2   institute_type    64958 non-null  object
 3   round_no          64958 non-null  int64 
 4   quota             64958 non-null  object
 5   pool              64958 non-null  object
 6   institute_short   64958 non-null  object
 7   program_name      64958 non-null  object
 8   program_duration  64958 non-null  object
 9   degree_short      64958 non-null  object
 10  category          64958 non-null  object
 11  opening_rank      64958 non-null  int64 
 12  closing_rank      64958 non-null  int64 
 13  is_preparatory    64958 non-null  int64 
dtypes: int64(6), object(8)
memory usage: 6.9+ MB


In [7]:
df.describe()

Unnamed: 0          year      round_no  opening_rank  closing_rank  \
count  64958.00000  64958.000000  64958.000000  6.495800e+04  6.495800e+04   
mean   32478.50000   2020.421580      2.609348  8.259642e+03  1.070497e+04   
std    18751.90373      1.149762      2.422558  2.679448e+04  3.788101e+04   
min        0.00000   2016.000000      1.000000  0.000000e+00  0.000000e+00   
25%    16239.25000   2020.000000      1.000000  6.710000e+02  8.320000e+02   
50%    32478.50000   2021.000000      1.000000  2.309000e+03  2.764500e+03   
75%    48717.75000   2021.000000      6.000000  6.932000e+03  8.190000e+03   
max    64957.00000   2021.000000      7.000000  1.082601e+06  1.144790e+06   

       is_preparatory  
count    64958.000000  
mean         0.047631  
std          0.212985  
min          0.000000  
25%          0.000000  
50%          0.000000  
75%          0.000000  
max          1.000000

In [8]:
df.loc[df["degree_short"] == "Int Msc.", "degree_short"] = "Int MSc."

In [9]:
df["degree_short"].nunique()

12

In [10]:
eval_College = df
eval_College.head()

Unnamed: 0  year institute_type  round_no quota            pool  \
0           0  2016            IIT         6    AI  Gender-Neutral   
1           1  2016            IIT         6    AI  Gender-Neutral   
2           2  2016            IIT         6    AI  Gender-Neutral   
3           3  2016            IIT         6    AI  Gender-Neutral   
4           4  2016            IIT         6    AI  Gender-Neutral   

  institute_short           program_name program_duration degree_short  \
0      IIT-Bombay  Aerospace Engineering          4 Years       B.Tech   
1      IIT-Bombay  Aerospace Engineering          4 Years       B.Tech   
2      IIT-Bombay  Aerospace Engineering          4 Years       B.Tech   
3      IIT-Bombay  Aerospace Engineering          4 Years       B.Tech   
4      IIT-Bombay  Aerospace Engineering          4 Years       B.Tech   

  category  opening_rank  closing_rank  is_preparatory  
0      GEN           838          1841               0  
1  OBC-NCL           408          1098               0  
2       SC           297           468               0  
3       ST            79           145               0  
4  GEN-PWD            94            94               0

In [11]:
eval_College['institute_type'] = [0 if x == 'IIT' else 1 for x in eval_College['institute_type']]
eval_College['institute_type'].unique()

array([0, 1], dtype=int64)

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
le = LabelEncoder()
eval_College['quota'] = le.fit_transform(eval_College['quota'])
eval_College['quota'].unique()

array([0, 3, 6, 1, 2, 4, 5])

In [14]:
eval_College['pool'] = [0 if x == 'Gender-Neutral' else 1 for x in eval_College['pool']]
eval_College['pool'].unique()
eval_College['category']= le.fit_transform(eval_College['category'])
eval_College['category'].unique()

array([0, 4, 6, 8, 3, 5, 7, 9, 1, 2])

In [15]:
y = eval_College[['institute_short', 'degree_short', 'program_name']]
y.head()

institute_short degree_short           program_name
0      IIT-Bombay       B.Tech  Aerospace Engineering
1      IIT-Bombay       B.Tech  Aerospace Engineering
2      IIT-Bombay       B.Tech  Aerospace Engineering
3      IIT-Bombay       B.Tech  Aerospace Engineering
4      IIT-Bombay       B.Tech  Aerospace Engineering

In [16]:
y = eval_College[['institute_short', 'degree_short', 'program_name']]
X = eval_College[['category', 'quota', 'pool', 'institute_type', 'round_no',
       'opening_rank', 'closing_rank']]

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8)


In [18]:
from sklearn.neighbors import KNeighborsClassifier


In [19]:
model = KNeighborsClassifier()
model.fit(X_train, y_train)

KNeighborsClassifier()

In [20]:
y_pred = model.predict(X_test)
y_pred

array([['NIT-Raipur', 'B.Tech', 'Mechanical Engineering'],
       ['NIT-Nagaland', 'B.Tech',
        'Electronics and Instrumentation Engineering'],
       ['IIT-Bombay', 'B.Tech', 'Aerospace Engineering'],
       ...,
       ['NIT-Raipur', 'B.Tech',
        'Electronics and Communication Engineering'],
       ['NIT-Allahabad', 'B.Tech', 'Electrical Engineering'],
       ['IIT-(BHU) Varanasi', 'B.Tech + M.Tech (IDD)',
        'Engineering Physics']], dtype=object)

In [21]:
Prediction1 = pd.DataFrame(model.predict([[0, 0, 0, 1, 6, 1000, 2841], [5, 5, 1, 0, 2, 1000, 1841]]), columns = [['College', 'Branch', 'Degree']])
Prediction1

College  Branch                  Degree
0      IIT-Delhi  B.Tech    Chemical Engineering
1  IIT-Hyderabad  B.Tech  Mechanical Engineering

In [22]:
import pickle

In [23]:
Pkl_Filename = "modeljee.pkl"  

with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(model, file)